### ISSUE TITLE
how to get camera parameters by 3x3 homography matrix output

### ISSUE THREAD

**Issue by ChenMinQi** [zhengthomastang/Cal_PnP#1]
Finally I run this program successfully and get the 3x3 homography matrix output. But in your [CAM_CAL_IPL](https://github.com/zhengthomastang/2018AICity_TeamUW/tree/master/Track1/CAM_CAL_IPL), the output is  intrinsic camera matrix, the rotation matrix, the translation vector and the projection matrix.
Can 3x3 homography matrix transfer to camera parameters?

**Comment by zhengthomastang** [comment]
You are right. But the homography matrix contains all the information you need to project points from a 3D plane to the 2D image plane. So the output of these two packages are essentially the same. All you need is to modify the part of code related to projection and back projection for your application. You can find a lot of resources from OpenCV if you search for homography-related functions.

**Comment by MrZilinXiao** [comment]
> You are right. But the homography matrix contains all the information you need to project points from a 3D plane to the 2D image plane. So the output of these two packages are essentially the same. All you need is to modify the part of code related to projection and back projection for your application. You can find a lot of resources from OpenCV if you search for homography-related functions.

I have some doubts: OpenCV provides cv::decomposeHomographyMat, but it needs more than  homography matrix, intrinsic camera calibration matrix, for example. Also it gives a set of possible answers but without any solutions to choose a correct one.

**Comment by zhengthomastang** [comment]
@MrZilinXiao To calculate the 3x4 projection matrix from 3x3 homgraphy, you will need extra information in the 3D space. In this PnP formulation, the points on the same 3D plane cannot provide sufficient information - You will need points not on the same plane.

**Comment by MrZilinXiao** [comment]
> @MrZilinXiao To calculate the 3x4 projection matrix from 3x3 homography, you will need extra information in the 3D space. In this PnP formulation, the points on the same 3D plane cannot provide sufficient information - You will need points not on the same plane.

That means this repo's output (i.e. homography) is not enough to calculate a 3x4 projection, right?

**Comment by zhengthomastang** [comment]
@MrZilinXiao Right. All the points on the same plane can only provide you with information for plane-to-plane transformation. Again you will need points on an additional plane.

**Comment by MrZilinXiao** [comment]
> @MrZilinXiao Right. All the points on the same plane can only provide you with information for plane-to-plane transformation. Again you will need points on an additional plane.

Forgive my following stupid question since I am just stepping into camera calibration...
Assuming I have already got points on another plane, are there any OpenCV built-in functions or some tricks to get a projection matrix? A tutorial link would be appreciated.

**Comment by zhengthomastang** [comment]
@MrZilinXiao If you have sufficient number of points (>= 11 as the projection matrix is 11 DoF), you can similarly solve the projection matrix as a system of linear equations. You can do this with all points on the same plane, but you will find out that the column corresponding to the Z axis (assuming Z=0 is the ground plane) is irrelevant.
