### ISSUE TITLE
getting zero reprojection error

### ISSUE THREAD

**Issue by poornimajd** [zhengthomastang/Cal_PnP#5]
I used four 2d points and corresponding 3d points,but when I run the code,I get 0 reprojection error.
Any suggestion is greatly appreciated.

Thank you

**Comment by zhengthomastang** [comment]
Four points are too few for PnP calibration. Note that there are only 8 unknowns in the homography matrix, so the 4 points will determine the matrix and there is no room for optimization. That's why the reprojection error is 0. I would recommend at least 10 points.
